name: Refresh API limit Daily

on:
  schedule:
    - cron: "*/5 * * * *" # daily at midnight
  workflow_dispatch:

jobs:
  refresh_usage_count:
    if: github.ref_name == 'prod'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: set timezone
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
          sudo timedatectl set-ntp true
          timedatectl

      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: prod

      - name: Install Mongoose
        run: npm install mongoose --legacy-peer-deps

      - name: Run refreshUsageCount script
        env:
          MONGO_URL: ${{ secrets.PROD_MONGO_URL }}
        run: node ./packages/app/scripts/refreshUsageCount.js
