name: Refresh API limit Daily

on:
  schedule:
    - cron: "*/2 * * * *" # every 2 minutes (UTC; Actions min granularity ~5 min)
  workflow_dispatch:

jobs:
  refresh_usage_count:
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: set timezone
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
          sudo timedatectl set-ntp true
          timedatectl

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Mongoose
        run: npm install mongoose --legacy-peer-deps

      - name: Run refreshUsageCount script
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: node ./packages/app/scripts/refreshUsageCount.js
